--- #YAML:1.0
name: Net-Proxy
version: 0.05
author:
  - Philippe 'BooK' Bruhat, C<< <book@cpan.org> >>.
abstract: Framework for proxying network connections in many ways
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
