---
abstract: 'Framework for proxying network connections in many ways'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  File::Find: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Builder: '0'
  Test::More: '0.88'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Proxy
requires:
  Carp: '0'
  Getopt::Long: '0'
  IO::Select: '0'
  IO::Socket::INET: '0'
  IO::Socket::SSL: '0'
  LWP::UserAgent: '0'
  POSIX: '0'
  Pod::Usage: '0'
  Scalar::Util: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Net-Proxy
  repository: http://github.com/book/Net-Proxy.git
version: '0.13'
